# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Administrador do Sistema', 'Administrador do Sistema'), ('Lider da Equipe', 'Lider da Equipe'), ('Promotor de Vendas', 'Promotor de Vendas')], max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Perfil de acesso ao sistema',
            },
        ),
    ]
