# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 00:53
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('perfil', models.CharField(choices=[('Administrador do sistema', b'Administrador do sistema'), ('Lider de equipe', b'Lider de equipe'), ('Promotor de Venda', b'Promotor de Venda')], max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=11)),
                ('propiedade', models.CharField(choices=[('Proprio', b'Proprio'), ('Empresa', b'Empresa')], max_length=150)),
                ('dias_jornada', models.CharField(choices=[('SEGUNDA-FEIRA', b'SEGUNDA-FEIRA'), ('TERCA-FEIRA', b'TERCA-FEIRA'), ('QUARTA-FEIRA', b'QUARTA-FEIRA'), ('QUINTA-FEIRA', b'QUINTA-FEIRA'), ('SEXTA-FEIRA', b'SEXTA-FEIRA'), ('SABADO', b'SABADO'), ('DOMINGO', b'DOMINGO')], max_length=150)),
                ('de', models.TimeField()),
                ('ate', models.TimeField()),
                ('inica_almoco', models.TimeField()),
                ('fim_almoco', models.TimeField()),
                ('matricula', models.CharField(max_length=15)),
                ('data_admissao', models.DateField()),
                ('tipo_remuneracao', models.CharField(choices=[('HORISTA', b'HORISTA'), ('MENSALISTA', b'MENSALISTA')], max_length=150)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
