# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0002_auto_20171221_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birt_day',
            field=models.DateField(verbose_name='nascmimento'),
        ),
    ]
