# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 03:27
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0002_auto_20180228_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dias_jornada',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'segunda', b'segunda'), (b'terca', b'terca'), (b'quarta', b'quarta'), (b'quinta', b'quinta'), (b'sexta', b'sexta'), (b'sabado', b'sabado'), (b'domingo', b'domingo')], max_length=48),
        ),
    ]
