# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0003_auto_20171221_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birt_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='nascmimento'),
        ),
    ]
