# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0004_auto_20171221_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
