# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-25 18:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0005_remove_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birt_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Nascmimento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Endereco de email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Ultimo Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.CharField(max_length=150, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='property_telphone',
            field=models.CharField(choices=[('Empresa', b'Empresa'), ('Colaborador', b'Colaborador'), ('Terceiros', b'Terceiros')], max_length=150, verbose_name='Propriedade do telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Obrigatorio. 15 caracteres ou menos. letras,                     numeros e estes caracteres @/./+/-/_', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'^[\\w.@+-]+$'), 'Use um nome de usuario valido.', 'Invalido')], verbose_name='username'),
        ),
    ]
