# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0006_auto_20171225_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=10, verbose_name='Senha'),
        ),
    ]
