# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0007_auto_20180130_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('Administrador do Sistema', b'Administrador do Sistema'), ('Lider da Equipe', b'Lider da Equipe'), ('Promotor de Vendas', b'Promotor de Vendas')], default=1, max_length=100, verbose_name='Perfil do Colaborador'),
            preserve_default=False,
        ),
    ]
