# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_na_Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=150)),
                ('data_adminissao', models.DateField()),
                ('tipo_remuneracao', models.CharField(choices=[('Horista', 'horista'), ('Mensalista', 'Mensalista')], max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Dados do Colaborador na Empresa',
            },
        ),
    ]
