# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_usuario', '0003_auto_20180301_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('colaboradores', models.ManyToManyField(to='app_equipe.Colaboradores')),
            ],
        ),
        migrations.CreateModel(
            name='Lideres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuario.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='lideres',
            field=models.ManyToManyField(to='app_equipe.Lideres'),
        ),
    ]
