# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 23:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_equipe', '0002_auto_20171221_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='jornada_equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
