# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-22 03:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=23)),
                ('porte', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Medio', 'Medio'), ('Grande', 'Grande')], max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('contato', models.CharField(max_length=150)),
                ('cargo_contato', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=150)),
                ('imagem_loja', models.ImageField(upload_to=b'')),
                ('observacao', models.TextField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clientes atendidos por colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Grupo_Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=150)),
                ('clientes', models.ManyToManyField(to='app_clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Segmento a que se enquadra o cliente',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clientes.Segmento'),
        ),
    ]
