# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0002_auto_20171225_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='latitude',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='longitude',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
